=== aosasona/vanity/web/templates/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://go.trulyao.dev/schemas/config.json",
  "required": [
    "domain",
    "port",
    "packages"
  ],
  "title": "go.trulyao.dev config schema",
  "type": "object",
  "properties": {
    "domain": {
      "type": "string",
      "description": "The domain name of the website"
    },
    "port": {
      "type": "integer",
      "description": "The port to run the server on",
      "default": 8080,
      "minimum": 1025,
      "maximum": 65535
    },
    "maxCacheAge": {
      "type": "integer",
      "description": "The maximum age of the cache in seconds",
      "default": 3600,
      "minimum": 0
    },
    "packages": {
      "type": "array",
      "description": "Available public packages",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the package"
          },
          "repo": {
            "type": "object",
            "description": "The package's repository details",
            "properties": {
              "host": {
                "type": "string",
                "description": "The host of the repository eg. github.com - no http:// or https:// prefix",
                "default": "github.com",
                "pattern": "^[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*$",
                "examples": [
                  "github.com",
                  "gitlab.com"
                ]
              },
              "owner": {
                "type": "string",
                "description": "The owner of the repository"
              },
              "name": {
                "type": "string",
                "description": "The name of the repository"
              }
            }
          },
          "type": {
            "type": "string",
            "description": "The type of package",
            "enum": [
              "module",
              "executable",
              "project"
            ]
          },
          "subPath": {
            "type": "string",
            "description": "This is useful if the package is a sub-package of another package, say you have one repo with multiple packages in it and you want to serve one particular package or customize the package root  e.g. github.com/user/repo/foo, this would be foo",
            "pattern": "(^[a-za-z0-9-_]+)((/+)([a-za-z0-9-_]+))+",
            "examples": [
              "foo",
              "foo/bar"
            ]
          },
          "readme": {
            "type": "string",
            "description": "A URL to the README file - accepts URI and relative paths",
            "format": "uri-reference",
            "default": "https://raw.githubusercontent.com/<user>/<repo>/master/README.md"
          }
        },
        "required": [
          "name",
          "repo"
        ]
      }
    }
  }
}

=== aosasona/vanity/config.json
{
  "$schema": "https://go.trulyao.dev/schemas/config.json",
  "port": 4096,
  "domain": "go.trulyao.dev",
  "maxCacheAge": 3600,
  "packages": [
    {
      "name": "vanity",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "vanity"
      },
      "type": "executable",
      "readme": "https://raw.githubusercontent.com/aosasona/vanity/master/README.md"
    },
    {
      "name": "mirror",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "mirror"
      },
      "type": "module",
      "readme": "https://raw.githubusercontent.com/aosasona/mirror/master/README.md"
    },
    {
      "name": "robin",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "robin"
      },
      "type": "module",
      "readme": "https://raw.githubusercontent.com/aosasona/robin/master/README.md"
    },
    {
      "name": "seer",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "seer"
      },
      "type": "module",
      "readme": "https://raw.githubusercontent.com/aosasona/seer/master/README.md"
    },
    {
      "name": "gots",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "gots"
      },
      "type": "module",
      "readme": "https://raw.githubusercontent.com/aosasona/gots/master/README.md"
    },
    {
      "name": "boilerplate",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "go-echo-boilerplate"
      },
      "type": "project",
      "readme": "https://raw.githubusercontent.com/aosasona/go-echo-boilerplate/master/README.md"
    },
    {
      "name": "lito",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "lito"
      },
      "type": "module",
      "readme": "https://raw.githubusercontent.com/aosasona/lito/master/README.md"
    },
    {
      "name": "bazooka",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "bazooka"
      },
      "type": "project",
      "readme": "https://raw.githubusercontent.com/aosasona/bazooka/master/README.md"
    },
    {
      "name": "b64",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "b64"
      },
      "type": "project",
      "readme": "https://raw.githubusercontent.com/aosasona/b64/master/README.md"
    },
    {
      "name": "interim",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "interim"
      },
      "type": "module",
      "readme": "https://raw.githubusercontent.com/aosasona/interim/master/README.md"
    },
    {
      "name": "logsnag",
      "repo": {
        "host": "github.com",
        "owner": "aosasona",
        "name": "logsnag.go"
      },
      "type": "module",
      "readme": "https://raw.githubusercontent.com/aosasona/logsnag.go/master/README.md"
    }
  ]
}
